- name: Get secret from vault
  connection: local
  hosts: localhost
  become: true
  tasks :
    - name: print
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=test/data/demo:username token={{vault_token}} url=http://vault.mikeydevops1.online:8200/') }}"
