

- hosts: labservers
  become: yes
  tasks:
    - name: 1st set of commands
      ansible.builtin.debug:
        msg: "1st set of commands"
      tags :
        - one
        -
    - name: 2nd set of commands
      ansible.builtin.debug:
        msg: "2nd set of commands"
      tags:
        - two
        -
    - name: 3srd set of commands
      ansible.builtin.debug:
        msg: "3rd set of commands"
      tags:
        - three




