

- hosts: labservers
  become: yes

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /tmp/newFile
        state: touch
      register: output

    - name: Show registered output
      ansible.builtin.debug:
        var: output

    - name: to retrive a non-existant file and ignore errors
      ansible.builtin.get_url:
        url: http://innaghiyev3c/index.html
        dest: /tmp/file2
      ignore_errors: yes

    - name: file is not found yet the next like is executed
      ansible.builtin.debug:
        msg: "next set of commands"

    - name: To retrive a non-existant file and using block and rescue method
      block:
      - name: Attempt to download the file
        ansible.builtin.get_url:
          url: "http://innaghiyev3c/index.html"
          dest: /tmp/file3
      rescue:
        ansible.builtin.debug:
          msg: "Failed to download the file, but rescued successfully!"

      always:
        ansible.builtin.debug:
          msg: "play done"




