

- hosts: labservers
  become: yes
  vars_files: ./users.yml
  vars:
    inv_file: /tmp/user_file_list.txt

  tasks:

    - name: Check if users.yml file exists
      ansible.builtin.stat:
        path: ./users.yml  # Replace with the path of your file
      register: file_status

    - name: 1st set of commands
      ansible.builtin.debug:
        var: faculty

    - name: change to template
      ansible.builtin.file:
        path: "{{ inv_file }}"
        state: touch

    - name: generate inventory
      ansible.builtin.lineinfile:
        path: "{{ inv_file }}"
        line: "{{ item | trim }}"
        create: yes
      loop: "{{ faculty }}"





