

- hosts: labservers
  become: yes
  tasks:
    - name: create file
      ansible.builtin.file:
          path: /tmp/newFile
          state: touch #to create a file
      register: output

    - name: Show registered output
      ansible.builtin.debug:
        var: {{ output }}

    - name: Add UID to the file
      ansible.builtin.lineinfile:
        path: /tmp/newFile
        line: "{{ output.uid }}"
