

- hosts: labservers
  become: yes
  vars:
    inv_file: /tmp/user_file_list.txt
  tasks:
    - name: 1st set of commands
      ansible.builtin.debug:
        msg: "1st set of commands"

    - name: change to template
      ansible.builtin.file:
        path: "{{ inv_file }}"
        state: touch

    - name: generate inventory
      ansible.builtin.lineinfile:
        path: "{{ inv_file }}"
        line: " {{ items}} "

      ansible.builtin.with_items:
        - " {{ staff }} "
        - " {{ faculty }} "
        - " {{ other }} "




