

- hosts: all
  become: yes
  vars_files: ./users.yml
  vars:
    inv_file: /tmp/user_file_list_new.txt

  tasks:

    - name: 1st set of commands
      ansible.builtin.set_fact:
        test_var: "{{ groups['labservers'] | join(', ') }}"
      ignore_error: yes
    - name: Debug the value of test_var
      ansible.builtin.debug:
        var: test_var



