

- hosts: labservers
  become: yes

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /tmp/newFile
        state: touch
      register: output

    - name: Show registered output
      ansible.builtin.debug:
        var: output

    - name: Add UID to the file
      ansible.builtin.lineinfile:
        path: /tmp/newFile
        line: "{{ items }} - is the uid"
      with_items:
        - sam
        - sana
        - mina




