

- hosts: labservers
  become: yes
  vars:
    inv_file: /tmp/testing_file.txt
  tasks:
    - name: 1st set of commands
      ansible.builtin.debug:
        msg: "1st set of commands"

    - name: change to template
      ansible.builtin.file:
        path: "{{ inv_file }}"
        state: touch

    - name: generate inventory
      ansible.builtin.lineinfile:
        path: "{{ inv_file }}"
        line: " {{ groups['labservers']|join(' ') }} "




