

- hosts: all
  become: yes
  vars_files: ./users.yml
  vars:
    inv_file: /tmp/user_file_list_new.txt

  tasks:
    - name: 1st set of commands
      ansible.builtin.debug:
        msg: hello
      test_var: {% for host in groups['web'] %}{{ host }}{% if not loop.last %}, {% endif %}{% endfor %}
      ansansible.builtin.debug:
        var: test_var





