

- hosts: labservers
  become: yes

  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /tmp/newFile
        state: touch
      register: output

    - name: Show registered output
      ansible.builtin.debug:
        var: output

    - name: to retrive a non-existant file and ignore errors
      ansible.builtin.get_url:
        url: http://innaghiyev3c/index.html
        dest: /tmp/file2
      ignore_errors: yes

    - name: file is not found yet the next like is executed
      ansible.builtin.debug:
        msg: "next set of commands"

    - name: To retrive a non-existant file and using block and rescue method
      block:
        ansible.builtin.get_url:
          src: "http://innaghiyev3c/index.html"
          desc: /tmp/file2
      rescue:
        - debug: msg= " the file does not exists! "
      always:
        - debug: msg=" Play done! "



