

- hosts: labservers
  become: yes
  tasks:
    - name: 1st set of commands
      ansible.builtin.debug:
        msg: "1st set of commands"

    - name: change to template
      ansible.builtin.template:
        src: templates/network.j2
        dest: /network_template.txt




