

- hosts: labservers
  become: yes
  handlers:
    - name: Checking handler 1
      ansible.builtin.debug:
        msg: " handler 1 is working"
      listen: "notify server"
  tasks:
    - name: Create file
      ansible.builtin.file:
        path: /tmp/newFile
        state: touch
      register: output

    - name: Show registered output
      ansible.builtin.debug:
        var: output

    - name: Add UID to the file
      ansible.builtin.lineinfile:
        path: /tmp/newFile
        line: "{{ output.uid }} - is the uid"

    - name: Add string using a condition
      ansible.builtin.lineinfile:
        path: /tmp/newFile
        line: "notify server"
      notify: "notify server"



